redis:
    host: localhost
    port: 6379
    db: 0

elasticsearch:
    hosts:
        - localhost

frame_handlers:
    COLLECT_FRAMES_FOR_CONTEXT:
        context: boat
        interval: 0.1

frame_grabber:
    redis_key: SERPENT:FRAMES

visual_debugger:
    redis_key_prefix: SERPENT:VISUAL_DEBUGGER
    available_buckets:
        - region_0
        - region_1
        - region_2
        - region_3
        - region_4
