redis:
    host: localhost
    port: 6379
    db: 0

frame_handlers:
    COLLECT_FRAMES_FOR_CONTEXT:
        context: character_select_screen
        interval: 0.1

frame_grabber:
    redis_key: PROJECT_EC:LATEST_FRAME

visual_debugger:
    redis_key_prefix: PROJECT_EC:VISUAL_DEBUGGER
    available_buckets:
        - flashback_1
        - flashback_2
        - flashback_3
        - flashback_4
        - flashback_5
        - flashback_6
