SerpentOpenRCT2GameAgentPlugin:
  frame_handler: PLAY
SerpentOpenRCT2GamePlugin:
  fps: 2
SerpentWorldOfGooGamePlugin:
  fps: 2
SerpentYouMustBuildABoatGameAgentPlugin:
  frame_handler: PLAY
  sfx_path: /home/serpent/SFX
SerpentYouMustBuildABoatGamePlugin:
  fps: 2
