BindingOfIsaacRebirthGameAgentPlugin: {collect_character_interval: 2, collect_frames_interval: 1,
  frame_handler: GAME_TRAIN, character: ISAAC, difficulty: NORMAL, seed: xh8czefw}

SuperHexagonGameAgentPlugin: {frame_handler: PLAY}
SuperHexagonGamePlugin: {frame_rate: 3}
YouMustBuildABoatGamePlugin: {steam_app_id: 290890}