redis:
    host: localhost
    port: 6379
    db: 0

elasticsearch:
    hosts:
        - localhost

frame_handlers:
    COLLECT_FRAMES_FOR_CONTEXT:
        context: level_gallery
        interval: 1

frame_grabber:
    redis_key: SERPENT:FRAMES

visual_debugger:
    redis_key_prefix: SERPENT:VISUAL_DEBUGGER
    available_buckets:
        - original_frame
        - svm_input
#        - A1
#        - A2
#        - A3
#        - A4
#        - A5
#        - A6
#        - A7
#        - A8
#        - B1
#        - B2
#        - B3
#        - B4
#        - B5
#        - B6
#        - B7
#        - B8
#        - C1
#        - C2
#        - C3
#        - C4
#        - C5
#        - C6
#        - C7
#        - C8
#        - D1
#        - D2
#        - D3
#        - D4
#        - D5
#        - D6
#        - D7
#        - D8
#        - E1
#        - E2
#        - E3
#        - E4
#        - E5
#        - E6
#        - E7
#        - E8
#        - F1
#        - F2
#        - F3
#        - F4
#        - F5
#        - F6
#        - F7
#        - F8