redis:
    host: localhost
    port: 6379
    db: 0

elasticsearch:
    hosts:
        - localhost

frame_handlers:
    COLLECT_FRAMES_FOR_CONTEXT:
        context: level_gallery
        interval: 1

frame_grabber:
    redis_key: SERPENT:FRAMES

visual_debugger:
    redis_key_prefix: SERPENT:VISUAL_DEBUGGER
    available_buckets:
        - original_frame
        - svm_input

sprites:
    seed: LULSUPCHAT